name       : ruby-mustache
version    : 1.1.0
release    : 1
source     :
    - https://github.com/mustache/mustache/archive/v1.1.0.tar.gz : 42797c2a8294c07b8c6bab327609cbb90bdc80c2ad0e8446ceb7b1fc61a4b3a3
license    : MIT
component  : programming.ruby
summary    : Mustache is a framework-agnostic way to render logic-free views.
description: |
    Inspired by ctemplate and et, Mustache is a framework-agnostic way to render logic-free views.

    As ctemplates says, "It emphasizes separating logic from presentation: it is impossible to embed application logic in this template language.

    Think of Mustache as a replacement for your views. Instead of views consisting of ERB or HAML with random helpers and arbitrary logic, your views are broken into two parts: a Ruby class and an HTML template.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby
build      : |
    %gem_build
install    : |
    %gem_install
